apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-demo-sb
  name: app-demo-sb
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9090
  selector:
    app: app-demo-sb